#Attempting to create a jenkins agent image .net core sdk and runtime
#Build the code
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out

#Use the jenkins agent and install asp.net runtime
FROM quay.io/openshift/origin-jenkins-agent-base

ENV NUGET_XMLDOC_MODE=skip \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

RUN yum install rh-dotnet22 -y /
    scl enable rh-dotnet22 bash

WORKDIR /app
COPY --from=build /app/out
ENTRYPOINT ["dotnet", "CoreApiContainer.dll"]
