#Attempting to create a jenkins agent image .net core sdk and runtime
#Build the code
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out

#Use the jenkins agent and install asp.net runtime
FROM quay.io/openshift/origin-jenkins-agent-base

# Don't download/extract docs for nuget packages
# Don't do initially populate of package cache
# Enable nodejs and dotnet scl
ENV DOTNET_CORE_VERSION=2.2 \
    BASH_ENV=/usr/local/bin/scl_enable \
    ENV=/usr/local/bin/scl_enable \
    PROMPT_COMMAND=". /usr/local/bin/scl_enable" \
    ENABLED_COLLECTIONS="rh-nodejs8 rh-dotnet22" \
    NUGET_XMLDOC_MODE=skip \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

COPY contrib/bin/scl_enable /usr/local/bin/scl_enable

# Install
RUN yum install -y centos-release-dotnet centos-release-scl-rh && \
    INSTALL_PKGS="rh-dotnet22 rh-nodejs8-npm" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y && \
# yum cache files may still exist (and quite large in size)
    rm -rf /var/cache/yum/*

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001

WORKDIR /app
COPY --from=build /app/out
ENTRYPOINT ["dotnet", "CoreApiContainer.dll"]
