#Attempting to create a jenkins agent image .net core sdk and runtime
#Build the code
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out

#Use the jenkins agent and install asp.net runtime
#FROM quay.io/openshift/origin-jenkins-agent-base
FROM image-registry.openshift-image-registry.svc:5000/default/dotnet-22-jenkins-slave-rhel7:latest

WORKDIR /app
COPY --from=build /app/out
ENTRYPOINT ["dotnet", "CoreApiContainer.dll"]
