apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dotnet-api
  labels:
    app: dotnet-api
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: dotnet-api
  template:
    metadata: 
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: dotnet-api
          imagePullPolicy: Never
          env:
            -  name: ASPNETCORE_URLS
               value: 'http://*:8080'